question_data = [{"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy", "question": "Snakes and Ladders was originally created in India?", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                     "question": "In the 1988 film 'Akira', Tetsuo ends up destroying Tokyo.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                     "question": "The music group Daft Punk got their name from a negative review they recieved.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004's 'The Aviator'.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Vatican City is a country.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "The S in Harry S. Truman stands for 'Samuel'.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "In 2016, the United Kingdom voted to stay in the EU.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                  "question": "Stephen Chbosky wrote the book 'The Perks of Being A Wallflower'.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Cats have whiskers under their legs.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Art", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo da Vinci was not the creator of the Mona Lisa.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The game 'Pocket Morty' has a Morty called 'Pocket Mortys Morty'?", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                  "question": "Psychology is the science of behavior and mind.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy", "question": "The Python programming language gets its name from the British comedy group 'Monty Python.'", "correct_answer": "True", "incorrect_answers": ["False"]}]
